services:
  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: task_management
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - task-net

  app:
    build:
      context: .
    container_name: task-management-app
    depends_on:
      - db
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/task_management
      SPRING_DATASOURCE_PASSWORD: pass
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - task-net

volumes:
  postgres-data:

networks:
  task-net:
    driver: bridge
